### ISSUE TITLE
base ux/ui issues

### ISSUE THREAD

**Issue by SeGeGha** [vitaliykharlamov/weather-forecast#1]
1. При загрузке страницы плющит кнопку переключения фонового изображения и поле ввода локации. Желательно такие вещи фиксить.
![image](https://user-images.githubusercontent.com/21230284/191265109-1efd202e-2338-4d0e-95e5-7c7f129f50df.png)

2. Дата переводится с заглушки на сегодняшнюю с задержкой 1с - бросается в глаза. Как вариант, при загрузке приложения запускать модуль по обновлению времени сразу же и после уже регистрировать интервал.

3. Для одного и того же разрешения прыгает экран в зависимости от запроса. Как варианты фиксов: 
- задать минимальную высоту блоку = 2 строки текста
- выводить в 1 строку, но обрезать всё что вылазит из строки
![Screenshot_3](https://user-images.githubusercontent.com/21230284/191266103-1f9c9bc9-5eb3-4d97-a276-706e858fcada.png)
![Screenshot_4](https://user-images.githubusercontent.com/21230284/191266125-6bede34c-bac5-4c09-9658-b2ee3e777ab2.png)

**Comment by vitaliykharlamov** [comment]
Все эти замечания пофиксил.
