### ISSUE TITLE
code issues

### ISSUE THREAD

**Issue by SeGeGha** [vitaliykharlamov/weather-forecast#2]
1. connectLocalStorage - начинаем с действия
![image](https://user-images.githubusercontent.com/21230284/191268266-2130d830-fab5-4748-b000-7793aa10e0b6.png)

2.  Если с запросом будет "не ок",  то нам вернется undefined. Надо или в функциях "connect..." докручивать проверки на получение данных либо можно добавить принудительный выход `if (!todayWeather) return`, чтоб ничего не ломалось (так со всеми запросами)
![image](https://user-images.githubusercontent.com/21230284/191279016-8cd486a1-a198-449f-9c15-4006ff2c81c9.png)

3. weather можно вытянуть тоже из todayWeather.data[0]
```
const { weather, temp: temperature, rh: humidity, pres: pressure, wind_spd: windSpeed } = todayWeather.data[0];
const { description: description, icon: imgName } = weather;
```
![image](https://user-images.githubusercontent.com/21230284/191279539-fb690d92-c062-45aa-ac9b-446893eb66a9.png)

4. Не баг, а для интереса: такие вещи теперь можно делать с помощью нового оператора ?? https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator
![image](https://user-images.githubusercontent.com/21230284/191280294-6dfcdd51-af5e-4138-9bb3-aedf79d989f9.png)

5. classList.toggle() юзать в таких случаях
![image](https://user-images.githubusercontent.com/21230284/191280769-dc7cdedf-62b6-4abf-9cbb-9557bafcc67c.png)

6. Когда i станет равным images.length последующие клики буду сломаны в этом месте images[i].url_h
тут нужно обнулять i при превышении длины
```
id = (id + 1) % images.length
```
![image](https://user-images.githubusercontent.com/21230284/191281092-19c38045-14db-4e9c-9fbd-f3b1db5c358c.png)

7. Еще бы дизейблить кнопку смены фона пока не выполнилась предыдущая смена.

**Comment by vitaliykharlamov** [comment]
Все замечания пофиксил.
